apiVersion: v1
kind: Pod
metadata:
  name: iptables-pod
  namespace: intersoul
spec:
  hostNetwork: true
  containers:
  - name: iptables-container
    image: busybox
    securityContext:
      privileged: true
    command: ["/bin/sh", "-c", "sleep infinity"]